### ISSUE TITLE
Upgrading to 2.0.0 fails on migrations with a swapped Application model

### ISSUE THREAD

**Issue by wjn0** [jazzband/django-oauth-toolkit#1168] opened 2022-06-01 16:57 UTC
**Describe the bug**
Upgrading to version 2.0.0 when a swapped Application model is already in place results in a failure to migrate.

**To Reproduce**
Upgrade from 1.x to 2.0 and run the `makemigrations` and `migrate` commands.

**Expected behavior**
Should be able to upgrade and migrate the database as required.

**Version**
2.0.0

- [x] I have tested with the latest published release and it's still a problem.
- [ ] I have tested with the master branch and it's still a problem.

**Additional context**
Stack trace on `migrate`:

```
0.000) INSERT INTO "django_migrations" ("app", "name", "applied") VALUES ('oauth2_provider', '0005_auto_20211222_2352', '2022-06-01T16:36:25.389510+00:00'::timestamptz) RETURNING "django_migrations"."id"; args=('oauth2_provider', '0005_auto_20211222_2352', datetime.datetime(2022, 6, 1, 16, 36, 25, 389510, tzinfo=<UTC>))
  Applying oauth2_provider.0005_auto_20211222_2352... OK
  Applying oauth2_provider.0006_alter_application_client_secret...Traceback (most recent call last):
  File "manage.py", line 21, in <module>
    main()
  File "manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/home/me/.local/lib/python3.7/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/home/me/.local/lib/python3.7/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/me/.local/lib/python3.7/site-packages/django/core/management/base.py", line 330, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/me/.local/lib/python3.7/site-packages/django/core/management/base.py", line 371, in execute
    output = self.handle(*args, **options)
  File "/home/me/.local/lib/python3.7/site-packages/django/core/management/base.py", line 85, in wrapped
    res = handle_func(*args, **kwargs)
  File "/home/me/.local/lib/python3.7/site-packages/django/core/management/commands/migrate.py", line 245, in handle
    fake_initial=fake_initial,
  File "/home/me/.local/lib/python3.7/site-packages/django/db/migrations/executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/home/me/.local/lib/python3.7/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/home/me/.local/lib/python3.7/site-packages/django/db/migrations/executor.py", line 227, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/home/me/.local/lib/python3.7/site-packages/django/db/migrations/migration.py", line 124, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/home/me/.local/lib/python3.7/site-packages/django/db/migrations/operations/special.py", line 190, in database_forwards
    self.code(from_state.apps, schema_editor)
  File "/home/me/.local/lib/python3.7/site-packages/oauth2_provider/migrations/0006_alter_application_client_secret.py", line 13, in forwards_func
    applications = Application.objects.all()
  File "/home/me/.local/lib/python3.7/site-packages/django/db/models/manager.py", line 191, in __get__
    cls._meta.swapped,
AttributeError: Manager isn't available; 'oauth2_provider.Application' has been swapped for 'users.JWTEnabledApplication'
```

**Comment by n2ygk** [comment] 2022-06-01 17:00
Duplicate of pinned issue #1146

**Closed by n2ygk** 2022-06-01 17:00 UTC
Labels: bug
